<h2>McCulloh Pitts Neuron </h2>

In [1]:
from random import choice
from numpy import array, dot, random
import numpy as np

In [2]:
#MCNeuron Neuron for AND Gate
w = random.rand(2)
w[1] = 1
w[0] = 1

training_data = [
                 (array([0, 0]), 0),
                 (array([0, 1]), 0),
                 (array([1, 0]), 0),
                 (array([1, 1]), 1),
]

step_function = lambda x: 0 if x < 2 else 1 #Step function with threshold of 1
#No bias layer in this neuron

In [3]:
for x, _ in training_data:
  result = dot(x, w)

  print("{}: {} -> {}".format(x[:2], result, step_function(result)))

[0 0]: 0.0 -> 0
[0 1]: 1.0 -> 0
[1 0]: 1.0 -> 0
[1 1]: 2.0 -> 1


In [4]:
# MCNeuron Neuron for OR Gate
w = random.rand(2)
w[1] = 1
w[0] = 1

training_data = [
                 (array([0, 0]), 0),
                 (array([0, 1]), 1),
                 (array([1, 0]), 1),
                 (array([1, 1]), 1),
]

step_function = lambda x: 0 if x < 1 else 1 #Step function with threshold of 1
#No bias layer in this neuron

In [5]:
for x, _ in training_data:
  result = dot(x, w)

  print("{}: {} -> {}".format(x[:2], result, step_function(result)))

[0 0]: 0.0 -> 0
[0 1]: 1.0 -> 1
[1 0]: 1.0 -> 1
[1 1]: 2.0 -> 1


<h2>Rosenblat's Neuron</h2>

In [11]:
# Rosenblat's Neuron for AND Gate
step_function = lambda x: 0 if x < 50 else 1 #step function with threshold of 0.5

training_data = [
            (array([0, 0, 1]), 0),
            (array([0, 1, 1]), 0),
            (array([1, 0, 1]), 0),
            (array([1, 1, 1]), 1)
]

w = random.rand(3)
b = .1
errors = []
eta = 0.1
n = 10000

for i in range(n):
  x, expected = choice(training_data)

  #w = np.append(w, b)

  result = dot(w, x)
  error = expected - step_function(result)
  errors.append(error)
  w += eta * error * x
  
for x, _ in training_data:
  result = dot(x, w)
  print("{}: {} -> {}".format(x[:3], result, step_function(result)))

  print(w)

[0 0 1]: 16.7892009263859 -> 0
[16.7168035  16.70163771 16.78920093]
[0 1 1]: 33.49083863333163 -> 0
[16.7168035  16.70163771 16.78920093]
[1 0 1]: 33.50600442883708 -> 0
[16.7168035  16.70163771 16.78920093]
[1 1 1]: 50.207642135782805 -> 1
[16.7168035  16.70163771 16.78920093]


In [12]:
# Rosenblatt's Neuron for OR Gate
step_function = lambda x: 0 if x < 50 else 1 #step function with threshold of 0.5

training_data = [
            (array([0, 0, 1]), 0),
            (array([0, 1, 1]), 1),
            (array([1, 0, 1]), 1),
            (array([1, 1, 1]), 1)
]

w = random.rand(3)
b = .1
errors = []
eta = 0.1
n = 10000

for i in range(n):
  x, expected = choice(training_data)

  #w = np.append(w, b)

  result = dot(w, x)
  error = expected - step_function(result)
  errors.append(error)
  w += eta * error * x
  
for x, _ in training_data:
  result = dot(x, w)
  print("{}: {} -> {}".format(x[:3], result, step_function(result)))

  print(w)

[0 0 1]: 31.12101702068867 -> 0
[19.15467768 19.02416638 31.12101702]
[0 1 1]: 50.14518339678794 -> 1
[19.15467768 19.02416638 31.12101702]
[1 0 1]: 50.27569470479207 -> 1
[19.15467768 19.02416638 31.12101702]
[1 1 1]: 69.29986108089135 -> 1
[19.15467768 19.02416638 31.12101702]


In [21]:
# Rosenblatt's Neuron for XOR Gate
step_function = lambda x: 0 if x < 50 else 1 #step function with threshold of 0.5

training_data = [
            (array([0, 0, 1]), 1),
            (array([0, 1, 1]), 0),
            (array([1, 0, 1]), 0),
            (array([1, 1, 1]), 1)
]

w = random.rand(3)
b = .1
errors = []
eta = 0.1
n = 10000

for i in range(n):
  x, expected = choice(training_data)

  #w = np.append(w, b)

  result = dot(w, x)
  error = expected - step_function(result)
  errors.append(error)
  w += eta * error * x
  
for x, _ in training_data:
  result = dot(x, w)
  print("{}: {} -> {}".format(x[:3], result, step_function(result)))

  print(w)
  #never right answer

[0 0 1]: 50.06958370714038 -> 1
[ 0.06948384  0.10280959 50.06958371]
[0 1 1]: 50.172393292662505 -> 1
[ 0.06948384  0.10280959 50.06958371]
[1 0 1]: 50.13906754658277 -> 1
[ 0.06948384  0.10280959 50.06958371]
[1 1 1]: 50.2418771321049 -> 1
[ 0.06948384  0.10280959 50.06958371]
